### ISSUE TITLE
NTREXBitextMining KeyError

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1018]
```bash
ERROR:mteb.evaluation.MTEB:Error while evaluating NTREXBitextMining: 'sna_Latn-est_Latn'
Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 370, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 118, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 388, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 367, in run
    mteb_task_result = MTEBResults.from_task_results(
  File "/data/niklas/mteb/mteb/load_results/mteb_results.py", line 89, in from_task_results
    eval_langs = subset2langscripts[hf_subset]
KeyError: 'sna_Latn-est_Latn'
```

**Comment by KennethEnevoldsen** [comment]
For ref #1014
