### ISSUE TITLE
RerankingEvaluator._encode_unique_texts() got an unexpected keyword argument 'batch_size'

### ISSUE THREAD

**Issue by dleemiller** [embeddings-benchmark/mteb#1056]
I was running an evaluation, and I think I found an issue with a recent change starting from v1.12.66

```2024-07-06 11:09:38.842489 >>> MindSmallReranking
Traceback (most recent call last):
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 382, in run
    results, tick, tock = self._run_eval(
                          ^^^^^^^^^^^^^^^
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 259, in _run_eval
    results = task.evaluate(
              ^^^^^^^^^^^^^^
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/abstasks/AbsTask.py", line 118, in evaluate
    scores[hf_subset] = self._evaluate_subset(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/abstasks/AbsTaskReranking.py", line 40, in _evaluate_subset
    scores = evaluator(model)
             ^^^^^^^^^^^^^^^^
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/evaluation/evaluators/RerankingEvaluator.py", line 74, in __call__
    scores = self.compute_metrics(model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/evaluation/evaluators/RerankingEvaluator.py", line 79, in compute_metrics
    self.compute_metrics_batched(model)
  File "/home/lee/anaconda3/envs/wordllama/lib/python3.11/site-packages/mteb/evaluation/evaluators/RerankingEvaluator.py", line 115, in compute_metrics_batched
    all_query_embs = self._encode_unique_texts(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RerankingEvaluator._encode_unique_texts() got an unexpected keyword argument 'batch_size'
```

After reverting to v1.12.65, the MindSmallReranking tasks completes successfully.

**Comment by KennethEnevoldsen** [comment]
Thanks for the issue @dleemiller. The break is because we have now changed from only allowing users to pass in certain arguments e.g. batch_size. However, we have since changed it to allow passing in arguments to the encode_kwargs. Seems like one case was not handled I have added fix in #1058 - assuming all test pass it will auto-merge. Let me know if you still experience issues afterwards.
