### ISSUE TITLE
FP16 embeddings fail with BitextMining

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1064]
Benchmarking 'intfloat/e5-mistral-7b-instruct' on `IN22GenBitextMining` fails for me with the below. I think it is related to its embeddings being in FP16. We could cast them to FP32 via .float() or maybe there's a better solution 

```
Encoding 23x1024 sentences: 100%|██████████| 23/23 [01:56<00:00,  4.08s/it]
Encoding 23x1024 sentences: 100%|██████████| 23/23 [01:56<00:00,  5.08s/it]

Matching sentences:   0%|          | 0/506 [00:00<?, ?it/s]INFO:mteb.evaluation.evaluators.BitextMiningEvaluator:Finding nearest neighbors...

Matching sentences:   0%|          | 0/506 [00:00<?, ?it/s]
ERROR:mteb.evaluation.MTEB:Error while evaluating IN22GenBitextMining: "addmm_impl_cpu_" not implemented for 'Half'
Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 389, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 130, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 421, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 369, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 259, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mteb/mteb/abstasks/AbsTaskBitextMining.py", line 47, in evaluate
    scores = self._evaluate_subset(
  File "/data/niklas/mteb/mteb/abstasks/AbsTaskBitextMining.py", line 93, in _evaluate_subset
    metrics = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 42, in __call__
    scores = self.compute_metrics(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 65, in compute_metrics
    scores[f"{key1}-{key2}"] = self._compute_metrics(
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 83, in _compute_metrics
    nearest_neighbors = self._similarity_search(embeddings1, embeddings2, top_k=1)
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 146, in _similarity_search
    cos_scores = score_function(
  File "/data/niklas/mteb/mteb/evaluation/evaluators/utils.py", line 34, in cos_sim
    return torch.mm(a_norm, b_norm.transpose(0, 1))
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

**Comment by KennethEnevoldsen** [comment]
Hmm will just add a test for this. For now I think the easiest thing it to convert it, but we do have an issue on standardizing to an API spec: https://github.com/embeddings-benchmark/mteb/issues/941
