### ISSUE TITLE
Adding model to automated evaluation

### ISSUE THREAD

**Issue by vprelovac** [embeddings-benchmark/mteb#107]
I would like to add Universal Sentence Encoder family of models to the automated evaluation.

It is relatively simply to evaluate it (thanks for making it straightforward), but it is not clear how to create a pull request to add the model to automated evaluation on the website. Please advise.

```
# !pip install tensorflow_text 

import tensorflow_hub as hub
from tensorflow_text import SentencepieceTokenizer
import tensorflow as tf

embedder=hub.load("https://tfhub.dev/google/universal-sentence-encoder-large/5")

class USE():
    def encode(self, sentences, batch_size=256, **kwargs):
        embeddings = []
        for i in range(0, len(sentences), batch_size):
            batch_sentences = sentences[i:i+batch_size]
            batch_embeddings = embedder(batch_sentences)
            embeddings.extend(batch_embeddings)
        return embeddings


model = USE()
```

**Comment by Muennighoff** [comment]
Nice! There is no automated evaluation - i.e. you have to evaluate the model yourself and then follow the instructions here https://github.com/embeddings-benchmark/mteb#leaderboard to add it to the leaderboard. You can just create a model without files except a README where you add the metadata

**Comment by vprelovac** [comment]
> Copy the content of the mteb_metadata.md file to the top of a README.md file of your model on the Hub. See [here](https://huggingface.co/Muennighoff/SGPT-5.8B-weightedmean-msmarco-specb-bitfit/blob/main/README.md) for an example.

This step is not clear. What is the model is not on the hub, like USE?

**Comment by Muennighoff** [comment]
> > Copy the content of the mteb_metadata.md file to the top of a README.md file of your model on the Hub. See [here](https://huggingface.co/Muennighoff/SGPT-5.8B-weightedmean-msmarco-specb-bitfit/blob/main/README.md) for an example.
> 
> This step is not clear. What if is the model is not on the hub, like USE?
> 
> Which step actually adds the data in the leaderboard ?

In that case you can just create an empty model on your account, add a README and add the contents there.

**Comment by vprelovac** [comment]
Do you mean create an account on huggingface, then create an empty model and add the readme on the top?

How will the MTEB leaderboard "know" that I did that?

**Comment by Muennighoff** [comment]
Yeah that would work; It scans all repo's with the tag `mteb` which is in the metadata.

**Comment by vprelovac** [comment]
Makes sense, I will be adding all of USE family soon.

**Comment by Muennighoff** [comment]
> Makes sense, I will be adding all of USE family soon.

Amazing! Looking forward to it!

**Comment by vprelovac** [comment]
Encountering two types of errors, any idea?

2023-04-24 03:11:34.439060 >>> TRECCOVID
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mteb/abstasks/AbsTaskRetrieval.py", line 95, in evaluate
    results = retriever.retrieve(corpus, queries)
  File "/usr/local/lib/python3.9/dist-packages/beir/retrieval/evaluation.py", line 23, in retrieve
    return self.retriever.search(corpus, queries, self.top_k, self.score_function, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/beir/retrieval/search/dense/exact_search.py", line 65, in search
    cos_scores = self.score_functions[score_function](query_embeddings, sub_corpus_embeddings)
  File "/usr/local/lib/python3.9/dist-packages/beir/retrieval/search/dense/util.py", line 11, in cos_sim
    a = torch.tensor(a)
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/framework/ops.py", line 1107, in __len__
    raise TypeError("Scalar tensor has no `len()`")
TypeError: Scalar tensor has no `len()`


2023-04-24 03:11:34.571244 >>> Touche2020
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mteb/evaluation/MTEB.py", line 225, in run
    task.load_data(eval_splits=task_eval_splits)
  File "/usr/local/lib/python3.9/dist-packages/mteb/abstasks/BeIRTask.py", line 50, in load_data
    self.corpus[split], self.queries[split], self.relevant_docs[split] = BeirDataLoader(
  File "/usr/local/lib/python3.9/dist-packages/beir/datasets/data_loader.py", line 63, in load
    self.check(fIn=self.query_file, ext="jsonl")
  File "/usr/local/lib/python3.9/dist-packages/beir/datasets/data_loader.py", line 30, in check
    raise ValueError("File {} not present! Please provide accurate file.".format(fIn))
ValueError: File /root/.cache/huggingface/datasets/BeIR/webis-touche2020/queries.jsonl not present! Please provide accurate file.

**Comment by Muennighoff** [comment]
The first one seems to be a problem with the embeddings you are returning - maybe it's just a single number? Can you share your encode function?

The second may be a caching problem - Can you delete `/root/.cache/huggingface/datasets/BeIR/webis-touche2020` & retry (so it redownloads)? Else you can also just manually download the queries.jsonl and put it in place from here: https://huggingface.co/datasets/BeIR/webis-touche2020/blob/main/queries.jsonl.gz

**Comment by vprelovac** [comment]
> Can you share your encode function?

It is in the first post in the thread. This happens with retrieval tasks only.

**Comment by vprelovac** [comment]
The data is ready. For some reason the refresh does not persist them?

https://huggingface.co/vprelovac/universal-sentence-encoder-multilingual-large-3
https://huggingface.co/vprelovac/universal-sentence-encoder-multilingual-3
https://huggingface.co/vprelovac/universal-sentence-encoder-4
https://huggingface.co/vprelovac/universal-sentence-encoder-large-5

That this sadly does not show, is that these models are 20x-50x faster than for example Instruct and yet at 80-90% performance.

**Comment by Muennighoff** [comment]
The below encode function works for me for the Retrieval datasets (just casting embeddings to numpy):
```python
    def encode(self, sentences, batch_size=32, **kwargs):
        embeddings = []
        for i in range(0, len(sentences), batch_size):
            batch_sentences = sentences[i:i+batch_size]
            batch_embeddings = embedder(batch_sentences)
            embeddings.extend(batch_embeddings.numpy())
        return embeddings
```


For the embedding dimension, you can just add a `config.json` file

```json
{
    "hidden_size": 768
}
```

where 768 is the embedding dimension
