### ISSUE TITLE
[mieb] VOC2007 not working

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1382]
```
ERROR:mteb.evaluation.MTEB:Error while evaluating VOC2007: An error occurred while generating t
he dataset
Traceback (most recent call last):
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/builder.py", line 1606, i
n _prepare_split_single 
    for key, record in generator:
  File "/data/huggingface/modules/datasets_modules/datasets/HuggingFaceM4--pascal_voc/5650e931b
d34da656f652750cad3cdcbd3a8eccd28b412d861d9d75028f5d7e7/pascal_voc.py", line 341, in _generate_
examples
    anno_infos = get_annotation(data_folder)
  File "/data/huggingface/modules/datasets_modules/datasets/HuggingFaceM4--pascal_voc/5650e931b
d34da656f652750cad3cdcbd3a8eccd28b412d861d9d75028f5d7e7/pascal_voc.py", line 190, in get_annota
tion
    anno_tree = ET.parse(anno_file)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/streaming.py", line 75, i
n wrapper
    return function(*args, download_config=download_config, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/utils/file_utils.py", lin
e 1267, in xet_parse
    return ET.parse(f, parser=parser)
  File "/env/lib/conda/gritkto4/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/env/lib/conda/gritkto4/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 79, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch
_size=1)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 394, in run
    task.load_data(eval_splits=task_eval_splits, **kwargs)
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 192, in load_data
    self.dataset = datasets.load_dataset(**self.metadata_dict["dataset"])  # type: ignore
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/datasets/load.py", line 2154, in l
oad_dataset

```

**Comment by gowitheflow-1998** [comment]
looks like this one is not relevant to datasets version like #1383 and it's runnable on my end. Does re-downloading the datasets help?

**Comment by Muennighoff** [comment]
Getting the below error with this dataset now for `nyu-visionx/moco-v3-vit-b`
```
Running evaluation for nyu-visionx/moco-v3-vit-b                                                             
WARNING:mteb.evaluation.MTEB:The `batch_size` argument is deprecated and will be removed in the next release.
 Please use `encode_kwargs = {'batch_size': ...}` to set the batch size instead.                             
────────────────────────────────────────────── Selected tasks  ──────────────────────────────────────────────
ImageMultilabelClassification                                                                                
    - VOC2007, i2i                                                                                           
                                                                                                             
                                                                                                             
  0%|                                                                                | 0/131 [00:00<?, ?it/s]
ERROR:mteb.evaluation.MTEB:Error while evaluating VOC2007: Unexpected type <class 'list'>
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 90, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=1)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskImageMultilabelClassification.py", line 111, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskImageMultilabelClassification.py", line 156, in _evaluate_subset
    _unique_train_embeddings = model.get_image_embeddings(
  File "/data/niklas/mieb/mteb/mteb/models/moco_models.py", line 82, in get_image_embeddings
    self.processor(batch_images)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 354,
 in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 465,
 in resize
    _, image_height, image_width = get_dimensions(img) 
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 80, 
in get_dimensions
    return F_pil.get_dimensions(img)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torchvision/transforms/_functional_pil.py", line
 31, in get_dimensions
    raise TypeError(f"Unexpected type {type(img)}")
TypeError: Unexpected type <class 'list'>

```

**Comment by isaac-chung** [comment]
Closing as this was run.
