### ISSUE TITLE
[mieb] 'BlipForImageTextRetrieval' object has no attribute 'get_image_features'

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1392]
```
ERROR:mteb.evaluation.MTEB:Error while evaluating CVBenchCount: 'BlipForImageTextRetrieval' object has no attribute 'get_image_features'
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 86, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=1)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 126, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2TextMultipleChoice.py", line 62, in _evaluate_subset
    scores = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2TextMultipleChoiceEvaluator.py", line 78, in __call__
    query_embeddings = model.get_fused_embeddings(
  File "/data/niklas/mieb/mteb/mteb/models/blip_models.py", line 123, in get_fused_embeddings
    image_embeddings = self.get_image_embeddings(images, batch_size)
  File "/data/niklas/mieb/mteb/mteb/models/blip_models.py", line 86, in get_image_embeddings
    image_outputs = self.model.get_image_features(**inputs)
  File "/env/lib/conda/gritkto4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'BlipForImageTextRetrieval' object has no attribute 'get_image_features'

```

**Comment by imenelydiaker** [comment]
I think it's an error here: https://github.com/embeddings-benchmark/mteb/blob/2b56317b73047d4a242f9b86f44f08c23b094011/mteb/models/blip_models.py#L86
`image_outputs` gets value of `vision_model(**inputs)` since BLIP model doesn't have a `get_image_features()` method or attribute (see https://github.com/huggingface/transformers/blob/ccbd57a8b665fbb5b1d566c0b800dc6ede509e8e/src/transformers/models/blip/modeling_blip.py#L1450).

Fix in this PR: https://github.com/embeddings-benchmark/mteb/pull/1394

**Comment by isaac-chung** [comment]
Closing this for now as the PR is merged.
