### ISSUE TITLE
[mieb] 'VLM2VecWrapper' object has no attribute 'calculate_probs'

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1416]
```
ERROR:mteb.evaluation.MTEB:Error while evaluating BirdsnapZeroShot: 'VLM2VecWrapper' object has no attribute 'calculate_probs'
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 91, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=32)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 126, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskZeroshotClassification.py", line 56, in _evaluate_subset
    metrics = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/ZeroshotClassificationEvaluator.py", line 82, in __call__
    probs = model.calculate_probs(text_embeddings, image_embeddings)
AttributeError: 'VLM2VecWrapper' object has no attribute 'calculate_probs'
(/env/lib/conda/gritkto4) niklas@dojo-a3-ghpc-55:/data/niklas/mieb/mteb$ 

```

**Comment by isaac-chung** [comment]
I can look into this. Which task was running?

**Comment by isaac-chung** [comment]
Closing this now. Feel free to reopen if the issue persists.
