### ISSUE TITLE
Evaluating LLM2Vec fails

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1422]
```
2024-11-09 21:39:44.994636: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-09 21:39:45.007613: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-09 21:39:45.011330: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
INFO:mteb.cli:Running with parameters: Namespace(model='McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-supervised', task_types=None, categories=None, tasks=['BornholmBitextMining'], languages=None, benchmarks=None, device=None, output_folder='/data/niklas/results/results', verbosity=2, co2_tracker=True, eval_splits=None, model_revision=None, batch_size=4, overwrite=False, save_predictions=False, func=<function run at 0x7fa223bac5e0>)

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]
Downloading shards:  50%|█████     | 2/4 [00:00<00:00, 16.79it/s]
Downloading shards: 100%|██████████| 4/4 [00:00<00:00, 17.53it/s]
Downloading shards: 100%|██████████| 4/4 [00:00<00:00, 17.40it/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:06,  2.17s/it]
Loading checkpoint shards:  50%|█████     | 2/4 [00:03<00:03,  1.58s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:04<00:01,  1.38s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.09it/s]
Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.17s/it]
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
─────────────────────────────── Selected tasks  ────────────────────────────────
BitextMining
    - BornholmBitextMining, s2s


INFO:mteb.evaluation.MTEB:

********************** Evaluating BornholmBitextMining **********************
INFO:mteb.evaluation.MTEB:Loading dataset for BornholmBitextMining
No config specified, defaulting to the single config: bornholmsk_parallel/BornholmskParallel
INFO:datasets.builder:No config specified, defaulting to the single config: bornholmsk_parallel/BornholmskParallel
Loading Dataset Infos from /data/huggingface/modules/datasets_modules/datasets/strombergnlp--bornholmsk_parallel/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
INFO:datasets.info:Loading Dataset Infos from /data/huggingface/modules/datasets_modules/datasets/strombergnlp--bornholmsk_parallel/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
Overwrite dataset info from restored data version if exists.
INFO:datasets.builder:Overwrite dataset info from restored data version if exists.
Loading Dataset info from /data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
INFO:datasets.info:Loading Dataset info from /data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
Found cached dataset bornholmsk_parallel (/data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815)
INFO:datasets.builder:Found cached dataset bornholmsk_parallel (/data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815)
Loading Dataset info from /data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
INFO:datasets.info:Loading Dataset info from /data/huggingface/datasets/strombergnlp___bornholmsk_parallel/BornholmskParallel/1.0.0/a93ddacca6042553271bf4c1c0e035df3fccf848c6820417766752d676567815
INFO:mteb.abstasks.AbsTaskBitextMining:
Task: BornholmBitextMining, split: test, subset: default. Running...

Encoding 2x500 sentences:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/125 [00:00<?, ?it/s][A
Batches:   0%|          | 0/125 [00:00<?, ?it/s]

Encoding 2x500 sentences:   0%|          | 0/2 [00:00<?, ?it/s]
ERROR:mteb.evaluation.MTEB:Error while evaluating BornholmBitextMining: 'LlamaBiModel' object has no attribute 'rotary_emb'
Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 387, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 145, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 477, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 301, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mteb/mteb/abstasks/AbsTaskBitextMining.py", line 82, in evaluate
    scores[hf_subet] = self._evaluate_subset(
  File "/data/niklas/mteb/mteb/abstasks/AbsTaskBitextMining.py", line 115, in _evaluate_subset
    metrics = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 42, in __call__
    scores = self.compute_metrics(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mteb/mteb/evaluation/evaluators/BitextMiningEvaluator.py", line 54, in compute_metrics
    embeddings[sub] = model.encode(
  File "/data/niklas/mteb/mteb/models/llm2vec_models.py", line 69, in encode
    return self.model.encode(sentences, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/llm2vec/llm2vec.py", line 361, in encode
    embeddings = self._encode(
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/llm2vec/llm2vec.py", line 447, in _encode
    embeddings = self.forward(features)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/llm2vec/llm2vec.py", line 227, in forward
    reps = self.model(**sentence_feature)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/peft/peft_model.py", line 538, in forward
    return self.get_base_model()(*args, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 921, in forward
    position_embeddings = self.rotary_emb(hidden_states, position_ids)
  File "/env/lib/conda/gritkto/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlamaBiModel' object has no attribute 'rotary_emb'

```

**Comment by sivareddyg** [comment]
@vaibhavad I know we had some hardware specific failures, do you think it's related to that.

**Comment by KennethEnevoldsen** [comment]
This can be run using:

```py
import mteb
meta = mteb.get_model_meta("McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp-supervised")
task=mteb.get_task("MassiveScenarioClassification", eval_splits=["test"], languages=["eng"]) # just a small dataset
res = mteb.evaluate(meta, task)
```
