### ISSUE TITLE
[mieb] TIGER-Lab/VLM2Vec-Full torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1457]
```
ERROR:mteb.evaluation.MTEB:Error while evaluating CVBenchCount: torch.cat(): expected a non-empty list of Tensors
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 91, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=32)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/AbsTask.py", line 126, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2TextMultipleChoice.py", line 62, in _evaluate_subset
    scores = evaluator(model, encode_kwargs=encode_kwargs)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2TextMultipleChoiceEvaluator.py", line 78, in __call__
    query_embeddings = model.get_fused_embeddings(
  File "/data/niklas/mieb/mteb/mteb/models/vlm2vec_models.py", line 276, in get_fused_embeddings
    fused_embeddings = torch.cat(all_fused_embeddings, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

```

**Comment by isaac-chung** [comment]
Investigating.

**Comment by isaac-chung** [comment]
Closing this now. Feel free to reopen if the issue persists.
