### ISSUE TITLE
get_descriptive_stats fails with BrightRetrieval task

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#1483]
Btw @Samoed, BrightRetrieval raises an error when computing descriptive stats:

```
Traceback (most recent call last):
  File "~/mteb/scripts/tasks_descriptive_tasks.py", line 29, in <module>
    stat = task.calculate_metadata_metrics()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mteb/mteb/abstasks/AbsTask.py", line 212, in calculate_metadata_metrics
    descriptive_stats[split] = self._calculate_metrics_from_split(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mteb/mteb/abstasks/AbsTaskRetrieval.py", line 341, in _calculate_metrics_from_split
    corpus.update(process_docs(self.corpus, hf_subset, split))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/mteb/mteb/abstasks/AbsTaskRetrieval.py", line 468, in process_docs
    f"{split}_{hf_subset}_{k}": v for k, v in collection[hf_subset][split].items()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by Samoed** [comment]
It seems that the `long_document` configuration is expected to have a `leetcode` split, but it doesn't

**Comment by Samoed** [comment]
It seems that different configurations have different splits, and some splits might be missing in certain configurations. I didn’t expect this
