### ISSUE TITLE
[ERROR] 'OpenAIWrapper' object has no attribute 'model'

### ISSUE THREAD

**Issue by yjoonjang** [embeddings-benchmark/mteb#1494]
Hello, I saw this error while trying to evaluate 'text-embedding-3-large'. Can I get some help please?

The full errors are:
```
Running task: ['Ko-StrategyQA', 'AutoRAGRetrieval', 'MIRACLRetrieval', 'PublicHealthQA', 'BelebeleRetrieval', 'MrTidyRetrieval', 'MultiLongDocRetrieval', 'XPQARetrieval'] / text-embedding-3-large on GPU 2 in process Process-1
INFO:mteb.evaluation.MTEB:

## Evaluating 8 tasks:
───────────────────────────────────────────────────────────────────────── Selected tasks  ─────────────────────────────────────────────────────────────────────────
Retrieval
    - Ko-StrategyQA, s2p
    - AutoRAGRetrieval, s2p
    - MIRACLRetrieval, s2p, multilingual 1 / 18 Subsets
    - PublicHealthQA, s2p, multilingual 1 / 8 Subsets
    - BelebeleRetrieval, s2p, multilingual 3 / 376 Subsets
    - MrTidyRetrieval, s2p, multilingual 1 / 11 Subsets
    - MultiLongDocRetrieval, s2p, multilingual 1 / 13 Subsets
    - XPQARetrieval, s2p, multilingual 3 / 36 Subsets


INFO:mteb.evaluation.MTEB:

********************** Evaluating Ko-StrategyQA **********************
INFO:mteb.evaluation.MTEB:Loading dataset for Ko-StrategyQA
INFO:mteb.abstasks.AbsTaskRetrieval:Loading Corpus...
INFO:mteb.abstasks.AbsTaskRetrieval:Loaded 9251 DEV Documents.
INFO:mteb.abstasks.AbsTaskRetrieval:Doc Example: {'id': '17th century-1', 'title': '17th century', 'text': '17세기는 1601년 1월 1일부터 1700년 12월 31일까지 지속된 세기입니다. 이 시기는 유럽의 근대 초기에 속하며, 바로크 문화 운동, 스페인 황금 시대의 후반부, 네덜란드 황금 시대, 루이 14세가 지배한 프랑스 왕정 시대, 과학 혁명, 세계 최초의 공기업이자 거대 기업인 네덜란드 동인도 회사, 일부 역사가에 따르면 일반 위기 등이 특징적인 시기였다. 가장 큰 군사적 분쟁은 30년 전쟁, 터키 대전쟁, 무굴-사파비 전쟁(무굴-사파비 전쟁(1622-23), 무굴-사파비 전쟁(1649-53)), 무굴-마라타 전쟁, 네덜란드-포르투갈 전쟁 등이었습니다. 또한 이 시기에는 은 매장지 개발 등 유럽의 아메리카 식민지 개척이 본격적으로 시작되어 부의 유럽 유입으로 인플레이션이 발생하기도 했습니다.'}
INFO:mteb.abstasks.AbsTaskRetrieval:Loading Queries...
INFO:mteb.abstasks.AbsTaskRetrieval:Loaded 592 DEV Queries.
INFO:mteb.abstasks.AbsTaskRetrieval:Query Example: {'id': '5c27625de0e7c35be856_0', 'text': '토니 베넷의 중간 이름은 무엇인가요?'}
ERROR:mteb.evaluation.MTEB:Error while evaluating Ko-StrategyQA: 'OpenAIWrapper' object has no attribute 'model'
'OpenAIWrapper' object has no attribute 'model'
```

**Comment by yjoonjang** [comment]
Can I get some help please? @Samoed @KennethEnevoldsen

**Comment by Samoed** [comment]
Can you provide a trace of the error?

**Comment by yjoonjang** [comment]
Yes, this is my code
```python
TASK_LIST_RETRIEVAL = [
    "Ko-StrategyQA",
    "AutoRAGRetrieval",
    "MIRACLRetrieval",
    "PublicHealthQA",
    "BelebeleRetrieval",
    "MrTidyRetrieval",
    "MultiLongDocRetrieval",
    "XPQARetrieval"
]

TASK_LIST_STS = []

TASK_LIST = (
    TASK_LIST_CLASSIFICATION
    + TASK_LIST_CLUSTERING
    + TASK_LIST_PAIR_CLASSIFICATION
    + TASK_LIST_RERANKING
    + TASK_LIST_RETRIEVAL
    + TASK_LIST_STS
)

model_names = [
    # 'Salesforce/SFR-Embedding-2_R', # 4096
    # "Alibaba-NLP/gte-Qwen2-7B-instruct", # 8192
    # "BAAI/bge-multilingual-gemma2", # 4096 -> mteb에 없음
    # "intfloat/e5-mistral-7b-instruct", # 4096
    # "intfloat/multilingual-e5-large-instruct", # 512
    "text-embedding-3-large", # 8191
    # 'Alibaba-NLP/gte-multilingual-base', 
    # 'intfloat/multilingual-e5-base', # 512
    # 'intfloat/multilingual-e5-large', # 512
    # "jinaai/jina-embeddings-v3", # 8192
    # "jhgan/ko-sroberta-multitask", # 128
    # "BAAI/bge-m3", # 8192
    # "nlpai-lab/KoE5", # 512
    # "dragonkue/BGE-m3-ko" # 8192
] + model_names

def evaluate_model(model_name, gpu_id):
    try:
        # Set the environment variable for the specific GPU
        os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
        
        model = None
        if not os.path.exists(model_name):
            if "m2v" in model_name:
                static_embedding = StaticEmbedding.from_model2vec(model_name)
                model = SentenceTransformer(modules=[static_embedding])
            else:
                model = mteb.get_model(model_name)
        else:
            file_name = os.path.join(model_name, "model.safetensors")
            if os.path.exists(file_name):
                if "m2v" in model_name:
                    static_embedding = StaticEmbedding.from_model2vec(model_name)
                    model = SentenceTransformer(modules=[static_embedding])
                else:
                    model = mteb.get_model(model_name)

        if model:
            setproctitle(f"{model_name}-{gpu_id}")
            print(f"Running task: {TASK_LIST} / {model_name} on GPU {gpu_id} in process {current_process().name}")
            evaluation = MTEB(
                tasks=get_tasks(tasks=TASK_LIST, languages=["kor-Kore", "kor-Hang", "kor_Hang"])
            )
            if "multilingual-e5" in model_name:
                batch_size = 128
            elif "jina" in model_name or "bge" in model_name:
                batch_size = 32
            else:
                batch_size = 64
            if args.quantize:
                evaluation.run(
                    model,
                    output_folder=f"/data_x/EMBEDDING/RESULTS/{model_name}-quantized",
                    encode_kwargs={"batch_size": batch_size, "precision": "binary"},
                )
            else:
                evaluation.run(
                    model,
                    output_folder=f"/data_x/EMBEDDING/RESULTS/{model_name}",
                    encode_kwargs={"batch_size": batch_size},
                )
    except Exception as ex:
        print(ex)

if __name__ == "__main__":
    num_gpus = 8
    processes = []
    for i, model_name in enumerate(model_names):
        gpu_id = (i+1)
        p = Process(target=evaluate_model, args=(model_name, gpu_id))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
```

Can this be a error due to multiprocessing?

**Comment by Samoed** [comment]
Can you provide full error trace from `errors_log.txt`?

**Comment by yjoonjang** [comment]
I used `traceback` and printed out the error. The errors are:
```bash
Error in model text-embedding-3-large on GPU 4: 'OpenAIWrapper' object has no attribute 'model'
Traceback:
Traceback (most recent call last):
  File "/mnt/raid6/yjoonjang/projects/Embedding-universe/KURE-train/evaluate.py", line 135, in evaluate_model
    evaluation.run(
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 477, in run
    raise e
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 438, in run
    results, tick, tock = self._run_eval(
                          ^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 301, in _run_eval
    results = task.evaluate(
              ^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 311, in evaluate
    retriever = RetrievalEvaluator(
                ^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/evaluators/RetrievalEvaluator.py", line 448, in __init__
    if is_cross_encoder_compatible(retriever):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/evaluators/RetrievalEvaluator.py", line 431, in is_cross_encoder_compatible
    op = getattr(model.model, "predict", None)
                 ^^^^^^^^^^^
AttributeError: 'OpenAIWrapper' object has no attribute 'model'


```

**Comment by yjoonjang** [comment]
+ I checked the issue you wrote and used the code. Thank you, @Samoed 
It worked well, but is there a method to truncate the text when using OpenAI embedding models?

I got the following error:
```bash
ERROR:mteb.evaluation.MTEB:Error while evaluating MIRACLRetrieval: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 8461 tokens (8461 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens, however you requested 8461 tokens (8461 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by Samoed** [comment]
I think that it needs to change the openai wrapper to trim tokens. I think that tiktoken had a tokenizer for this model

**Comment by yjoonjang** [comment]
I added a new list to the OpenAIWrapper. The codes are:
```python
class OpenAIWrapper(Wrapper):
    def __init__(self, model_name: str, embed_dim: int | None = None, **kwargs) -> None:
        requires_package(self, "openai", "Openai text embedding")
        from openai import OpenAI

        self._client = OpenAI()
        self._model_name = model_name
        self._embed_dim = embed_dim

    def num_tokens_from_string(string: str, encoding_name: str) -> int:
        """Returns the number of tokens in a text string."""
        encoding = tiktoken.get_encoding(encoding_name)
        num_tokens = len(encoding.encode(string))
        return num_tokens

    def encode(self, sentences: list[str], **kwargs: Any) -> np.ndarray:
        requires_package(self, "openai", "Openai text embedding")
        from openai import NotGiven

        if self._model_name == "text-embedding-ada-002" and self._embed_dim is not None:
            logger.warning(
                "Reducing embedding size available only for text-embedding-3-* models"
            )
        
        trimmed_sentences = []
        for sentence in sentences:
            encoding = tiktoken.get_encoding("cl100k_base")
            encoded_sentence = encoding.encode(sentence)
            if len(encoded_sentence) > 8192:
                trimmed_sentence = encoding.decode(encoded_sentence[:8192])
                trimmed_sentences.append(trimmed_sentence)
            else:
                trimmed_sentences.append(sentence)

        max_batch_size = 2048
        sublists = [
            sentences[i : i + max_batch_size]
            for i in range(0, len(sentences), max_batch_size)
        ]

        all_embeddings = []

        for sublist in sublists:
            response = self._client.embeddings.create(
                input=sublist,
                model=self._model_name,
                encoding_format="float",
                dimensions=self._embed_dim or NotGiven(),
            )
            all_embeddings.extend(self._to_numpy(response))

        return np.array(all_embeddings)

    def _to_numpy(self, embedding_response) -> np.ndarray:
        return np.array([e.embedding for e in embedding_response.data])
```

Would this be okay ?

- reference: https://platform.openai.com/docs/guides/embeddings/how-can-i-tell-how-many-tokens-a-string-has-before-i-embed-it#how-can-i-tell-how-many-tokens-a-string-has-before-i-embed-it

**Comment by Samoed** [comment]
I think so, but it would be better to pass the tokenizer name as a parameter to the class.

**Comment by yjoonjang** [comment]
Can I work on this? @Samoed

**Comment by Samoed** [comment]
Yes. It would be great if you update openai wrapper
