### ISSUE TITLE
How to make customized models evaluated with prompts or prefixes?

### ISSUE THREAD

**Issue by yjoonjang** [embeddings-benchmark/mteb#1506]
Hello, I am trying to evaluate a embedding model which is fine-tuned based on multilingual-e5-large.
Since the base model requires a prefix, think this model should also need a wrapper too.

Are there any references that I can look working on this ?
I've seen [this](https://github.com/embeddings-benchmark/mteb/issues/1491) but I think this is not accurately what I was looking for. 

Thank you.

**Comment by yjoonjang** [comment]
```python
import mteb
from mteb.encoder_interface import PromptType
import numpy as np
from mteb.models.wrapper import Wrapper

model_prompts = {
    PromptType.query.value: "query: ",
    PromptType.passage.value: "passage: ",
}

class CustomModel(Wrapper):
    def encode(
        self,
        sentences: list[str],
        task_name: str,
        prompt_type: PromptType | None = None,
        **kwargs,
    ) -> np.ndarray:
        """Encodes the given sentences using the encoder.
        
        Args:
            sentences: The sentences to encode.
            task_name: The name of the task.
            prompt_type: The prompt type to use.
            **kwargs: Additional arguments to pass to the encoder.
            
        Returns:
            The encoded sentences.
        """
        pass
```

I wrote this, but don't know how to pass the prompt when encoding. 
Can I get some help please?
Thank you.

**Comment by Samoed** [comment]
Here wrapper for e5 models https://github.com/embeddings-benchmark/mteb/blob/main/mteb%2Fmodels%2Fe5_models.py

**Comment by yjoonjang** [comment]
Thank you, @Samoed , now I get it.
Since there is no BAAI/bge-multilingual-gemma2 listed in mteb models, is it right to evaluate the model with the following code?
```python
model_name = "BAAI/bge-multilingual-gemma2"
model_prompts = {
    PromptType.query.value: "Given a web search query, retrieve relevant passages that answer the query.",
}
model = SentenceTransformerWrapper(model=model_name, model_prompts=model_prompts)
...
```
- reference: https://huggingface.co/BAAI/bge-multilingual-gemma2

**Comment by Samoed** [comment]
Bge gemma is an instruct model and you need to use InstructWrapper https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/instruct_wrapper.py

**Comment by yjoonjang** [comment]
Thank you, @Samoed 
I changed to the following code:
```python
instruction_template = '<instruct>{instruction}\n<query>'
model = instruct_wrapper(model_name_or_path=model_name, mode="instruct", instruction_template=instruction_template, use_cache=True)
```

and got this error:
```bash
INFO:mteb.abstasks.AbsTaskRetrieval:Subset: default
INFO:mteb.evaluation.evaluators.RetrievalEvaluator:Encoding Queries.
INFO:mteb.models.instruct_wrapper:Using instruction: '<instruct>Retrieve text based on user query.
<query>' for task: 'Ko-StrategyQA'
Batches:   0%|                                                                                                                                                                                      | 0/296 [00:00<?, ?it/s]
ERROR:mteb.evaluation.MTEB:Error while evaluating Ko-StrategyQA: Gemma2Model.forward() got an unexpected keyword argument 'is_causal'
Gemma2Model.forward() got an unexpected keyword argument 'is_causal'
Traceback (most recent call last):
  File "/mnt/raid6/yjoonjang/projects/Embedding-universe/KURE-train/evaluate.py", line 154, in evaluate_model
    evaluation.run(
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 477, in run
    raise e
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 438, in run
    results, tick, tock = self._run_eval(
                          ^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 301, in _run_eval
    results = task.evaluate(
              ^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 336, in evaluate
    scores[hf_subset] = self._evaluate_subset(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 345, in _evaluate_subset
    results = retriever(corpus, queries)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/evaluators/RetrievalEvaluator.py", line 491, in __call__
    return self.retriever.search(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/evaluators/RetrievalEvaluator.py", line 138, in search
    query_embeddings = self.model.encode(
                       ^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/evaluation/evaluators/RetrievalEvaluator.py", line 427, in encode
    return self.model.encode(
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/mteb/models/instruct_wrapper.py", line 67, in encode
    embeddings = super().encode(
                 ^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/gritlm/gritlm.py", line 133, in encode
    outputs = (
              ^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/raid6/yjoonjang/miniconda3/envs/mteb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Gemma2Model.forward() got an unexpected keyword argument 'is_causal'
```

**Comment by Samoed** [comment]
You need to use like this
```
instruct_wrapper(
        instruct_wrapper,
        model_name_or_path="BAAI/bge-multilingual-gemma2",
        instruction_template='<instruct>{instruction}\n<query>',
        attn="cccc",
        pooling_method="mean",
        mode="embedding",
        torch_dtype=torch.float16,
        normalized=True,
)
```

**Comment by yjoonjang** [comment]
Thank you. 
But shouldn't it be last token pooling?
https://huggingface.co/BAAI/bge-multilingual-gemma2#using-huggingface-transformers

**Comment by yjoonjang** [comment]
Really appreciate your help.
Thank you so much.
