### ISSUE TITLE
[mieb] Error message for unsupported models is unclear

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1632]
When trying to run e.g. moco on a task it does not support one gets the below error. I think we should catch this based on the metadata of the task (and maybe a new metadata field in models in terms of what they support / reuse the existing fields) to catch such errors and have a clean error message that it is not supported by this model

```
ERROR:mteb.evaluation.MTEB:Error while evaluating VidoreSyntheticDocQAAIRetrieval: mocov3_loader.<locals>.MOCOv3Wrapper.get_text_embeddings() got an unexpected keyword argument 'task_name'
Traceback (most recent call last):
  File "/data/niklas/mieb/mteb/scripts/run_mieb.py", line 100, in <module>
    results = evaluation.run(model, output_folder="/data/niklas/mieb/results-mieb-final", batch_size=8, overwrite_results=True)
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 464, in run
    raise e
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 425, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mieb/mteb/mteb/evaluation/MTEB.py", line 300, in _run_eval
    results = task.evaluate(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py", line 269, in evaluate
    scores[hf_subset] = self._evaluate_subset(
  File "/data/niklas/mieb/mteb/mteb/abstasks/Image/AbsTaskAny2AnyRetrieval.py", line 278, in _evaluate_subset
    results = retriever(corpus, queries)
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py", line 308, in __call__
    return self.retriever.search(
  File "/data/niklas/mieb/mteb/mteb/evaluation/evaluators/Image/Any2AnyRetrievalEvaluator.py", line 127, in search
    query_embeddings = self.model.get_text_embeddings(
TypeError: mocov3_loader.<locals>.MOCOv3Wrapper.get_text_embeddings() got an unexpected keyword argument 'task_name'
```

A current workaround is sth like the below to skip them
```
if ("moco" in model_name) or ("dinov2" in model_name):
    tasks = [task for task in tasks if "t" not in task.metadata.category]
```

**Comment by isaac-chung** [comment]
Looks like there's a misalignment on the function signature for the moco loader, otherwise this error would have been raised:
```
raise ValueError("MOCO models only support image encoding.")
```

We could certainly use a new/existing field to help filter what tasks the models support though.

**Comment by isaac-chung** [comment]
Merged into the latest MIEB commit.
