### ISSUE TITLE
Parallel retrieval is automatically selected during fabric training

### ISSUE THREAD

**Issue by Markus28** [embeddings-benchmark/mteb#177]
We train an embedding model using pytorch lightning fabric and we evaluate it periodically on MTEB during training. To this end, our model conforms to the default SentenceTransformer interface and exposes an `encode` method that accepts a list of strings and returns the embeddings as a numpy array.

On the TRECCOVID task, we get the following exception:

```
  File "/home/markus/finetuner-large-scale-training/large_scale_training/callbacks/evaluation_callback.py", line 138, in _run_sequential_evaluation
    results = self._mteb.run(
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 289, in run
    raise e
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 271, in run
    results = task.evaluate(model, split, **kwargs)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 81, in evaluate
    results = retriever.retrieve(corpus, queries)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 23, in retrieve
    return self.retriever.search(corpus, queries, self.top_k, self.score_function, **kwargs)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/beir/retrieval/search/dense/exact_search_multi_gpu.py", line 120, in search
    query_embeddings = torch.cat(query_embeddings, dim=0)
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray
```
This problem has emerged only recently, likely with commit 0dd82a9819d32f264a24dbc057f753efbf54e9d8. It also occurs during training on a single GPU.

It is our understanding that by using fabric, a `"RANK"` environment variable is set and we therefore use `DenseRetrievalParallelExactSearch` here: https://github.com/embeddings-benchmark/mteb/blob/fb90c022e11834ae6605f5bbb0a79af701793a96/mteb/abstasks/AbsTaskRetrieval.py#L70

I imagine that `DRPES` expects a different embedding format, namely a list of tensors, as opposed to a numpy array.
Currently, we are managing this problem by using a fork of MTEB which introduces an additional environment variable `"MTEB_SINGLE_GPU"`, guarding the branches here: https://github.com/embeddings-benchmark/mteb/blob/fb90c022e11834ae6605f5bbb0a79af701793a96/mteb/abstasks/AbsTaskRetrieval.py#L55 and here: https://github.com/embeddings-benchmark/mteb/blob/fb90c022e11834ae6605f5bbb0a79af701793a96/mteb/abstasks/BeIRTask.py#L26

We are now wondering whether the automatic selection of `DRPES` is intended, or whether this is an unexpected interference with lightning fabric. In the latter case, we would be happy to discuss possible solutions and raise a PR. Otherwise, we would be grateful for guidance on the correct `encode` interface in our specific case.

**Comment by Markus28** [comment]
Here is a minimal reproducible example:

```python
import os
import torch
import numpy as np
from lightning.fabric import Fabric
from transformers import AutoModel, AutoTokenizer
from torch.nn import functional as F
from mteb import MTEB

def average_pool(last_hidden_states, attention_mask):
    last_hidden = last_hidden_states.masked_fill(~attention_mask[..., None].bool(), 0.0)
    return last_hidden.sum(dim=1) / attention_mask.sum(dim=1)[..., None]


class EmbModel:
    def __init__(self, device='cuda'):
        self.device = device
        self.tokenizer = AutoTokenizer.from_pretrained('intfloat/multilingual-e5-base')
        self.model = AutoModel.from_pretrained('intfloat/multilingual-e5-base').to(device)

    @torch.inference_mode()
    def encode(self, input_texts, batch_size=None, **kwargs):
        batch_dict = self.tokenizer(input_texts, max_length=512, padding=True, truncation=True, return_tensors='pt').to(self.device)
        outputs = self.model(**batch_dict)
        embeddings = average_pool(outputs.last_hidden_state, batch_dict['attention_mask'])
        embeddings = F.normalize(embeddings, p=2, dim=1)
        return embeddings.cpu().numpy()

fabric = Fabric(devices=1, accelerator='cuda', strategy='deepspeed_stage_2')
fabric.launch()

model = EmbModel()
assert isinstance(model.encode(['Hello', 'foo bar']), np.ndarray)
print('RANK is set to', os.getenv('RANK'))
evaluation = MTEB(tasks=["TRECCOVID"])
results = evaluation.run(model)
```

We found that when using 
```python
model = SentenceTransformer("average_word_embeddings_komninos").to("cuda")
```
we get a different exception, namely

```
Traceback (most recent call last):
  File "/home/markus/finetuner-large-scale-training/runs/test.py", line 36, in <module>
    results = evaluation.run(model)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 289, in run
    raise e
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 271, in run
    results = task.evaluate(model, split, **kwargs)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/mteb/abstasks/AbsTaskRetrieval.py", line 81, in evaluate
    results = retriever.retrieve(corpus, queries)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/beir/retrieval/evaluation.py", line 20, in retrieve
    return self.retriever.search(corpus, queries, self.top_k, self.score_function, **kwargs)
  File "/home/markus/.cache/pypoetry/virtualenvs/large-scale-training-8_3_LJm3-py3.10/lib/python3.10/site-packages/beir/retrieval/search/dense/exact_search_multi_gpu.py", line 127, in search
    pool = self.model.start_multi_process_pool(self.target_devices)
AttributeError: 'DRESModel' object has no attribute 'start_multi_process_pool'
```

We are running MTEB version 1.1.1 and beir 2.0.0.

**Comment by Muennighoff** [comment]
Thanks a lot for reporting this! 
I think the automatic selection of `DRPES` is not intended - cc @NouamaneTazi - could you confirm?
If you could open a PR that would be amazing. 

Btw I plan to make some big changes to improve BEIR integration once I find some time, hopefully this year (https://github.com/embeddings-benchmark/mteb/issues/173#issuecomment-1802229530)

**Comment by Markus28** [comment]
I have opened a PR with a rather naive fix for the problem. It seems to work for us, but I'm not sure whether it is adequate on a larger scale.
