### ISSUE TITLE
BUCC KeyError

### ISSUE THREAD

**Issue by hyyp1** [embeddings-benchmark/mteb#308]
When I'm running BUCC dataset, an error occured：
Traceback (most recent call last):
  ```
File "d:\File_Manager_API\eval\eval_MTEB.py", line 6, in <module>
    results = evaluation.run(model, output_folder="D:\File_Manager_API\eval")
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\evaluation\MTEB.py", line 336, in run
    raise e
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\evaluation\MTEB.py", line 312, in run
    results = task.evaluate(
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\abstasks\AbsTaskBitextMining.py", line 36, in evaluate
    scores[lang] = self._evaluate_split(model, data_split, **kwargs)
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\abstasks\AbsTaskBitextMining.py", line 72, in _evaluate_split
    metrics = evaluator(model)
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\evaluation\evaluators\BitextMiningEvaluator.py", line 27, in __call__
    scores = self.compute_metrics(model)
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\evaluation\evaluators\BitextMiningEvaluator.py", line 36, in compute_metrics 
    embeddings1 = np.asarray([emb_dict[sent] for sent in self.sentences1])
  File "E:\anaconda\envs\agent\lib\site-packages\mteb\evaluation\evaluators\BitextMiningEvaluator.py", line 36, in <listcomp>      
    embeddings1 = np.asarray([emb_dict[sent] for sent in self.sentences1])
KeyError: 'Alles in allem erzielt jeder Dollar, der für Familienplanungsprogramme ausgegeben wird, sage und schreibe 120 Dollar an Nutzen.'
```

my code is below：
`from mteb import MTEB
from FlagEmbedding import BGEM3FlagModel

model = BGEM3FlagModel("D:\pretrained-model\\bge-m3",use_fp16=False)
evaluation = MTEB(tasks='BUCC')
results = evaluation.run(model, output_folder="D:\File_Manager_API\eval")`

Can anyone fix it up？

**Comment by KennethEnevoldsen** [comment]
Hi @hyyp1 when running:

```
from mteb import MTEB
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("average_word_embeddings_komninos")
mteb = MTEB(tasks='BUCC')

mteb.run(model, output_folder="tmp", overwrite_results=True)
```

I have no issues. Can you specify what version + what system you are on?

**Comment by hyyp1** [comment]
Hi，my OS is Windows 10 and mteb version is  1.5.0。
And this issues occured when the progress bars is over.

**Comment by KennethEnevoldsen** [comment]
Hmm the windows tests does not reproduce it and neither can I reproduce it locally. Does other datasets work fine?

**Comment by KennethEnevoldsen** [comment]
@hyyp1 as we haven't heard more and I can't reproduce the issue I will close this issue for now. Feel free to reopen it if it is still valid.
