### ISSUE TITLE
AttributeError: 'AmazonPolarityClassification' object has no attribute 'description'

### ISSUE THREAD

**Issue by austinmw** [embeddings-benchmark/mteb#336]
v1.5.5:

```
Traceback (most recent call last):
  File "/home/ubuntu/embeddings/FlagEmbedding/C_MTEB/eval_MTEB.py", line 34, in <module>
    task_names = [t.description["name"] for t in MTEB(task_types=args.task_type,
  File "/home/ubuntu/embeddings/FlagEmbedding/C_MTEB/eval_MTEB.py", line 34, in <listcomp>
    task_names = [t.description["name"] for t in MTEB(task_types=args.task_type,
AttributeError: 'AmazonPolarityClassification' object has no attribute 'description'
```

**Comment by isaac-chung** [comment]
It should now be accessed through `task.metadata.description`. Feel free to reopen this if the issue persists after a version bump.
