### ISSUE TITLE
BUG: The custom model example raises TypeError: MyModel.encode() missing 1 required positional argument: 'prompt'

### ISSUE THREAD

**Issue by codingl2k1** [embeddings-benchmark/mteb#679]
Following the instructions of Custom Model: https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-a-custom-model

The example code does not work.

``` python
from mteb import MTEB
import torch
import numpy as np
from typing import Any


class MyModel:
    def encode(
            self, sentences: list[str], prompt: str, **kwargs: Any
    ) -> torch.Tensor | np.ndarray:
        """Encodes the given sentences using the encoder.

        Args:
            sentences: The sentences to encode.
            prompt: The prompt to use. Useful for prompt-based models.
            **kwargs: Additional arguments to pass to the encoder.

        Returns:
            The encoded sentences.
        """
        pass


model = MyModel()
evaluation = MTEB(tasks=["Banking77Classification"])
evaluation.run(model)
```

raises:

``` Python
Error while evaluating Banking77Classification: MyModel.encode() missing 1 required positional argument: 'prompt'
Traceback (most recent call last):
  File "/Users/admin/Work/inference/benchmark/benchmark_rerank.py", line 26, in <module>
    evaluation.run(model)
  File "/Users/admin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 328, in run
    raise e
  File "/Users/admin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mteb/evaluation/MTEB.py", line 304, in run
    results = task.evaluate(
              ^^^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mteb/abstasks/AbsTaskClassification.py", line 88, in evaluate
    scores = self._evaluate_monolingual(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mteb/abstasks/AbsTaskClassification.py", line 144, in _evaluate_monolingual
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 318, in __call__
    model.encode(self.sentences_train, batch_size=self.batch_size)
TypeError: MyModel.encode() missing 1 required positional argument: 'prompt'
```

The mteb version:
```
Name: mteb
Version: 1.8.11
Summary: Massive Text Embedding Benchmark
```

**Comment by Muennighoff** [comment]
I think you can just remove the prompt kwarg.

I'm not sure why we added it in this PR https://github.com/embeddings-benchmark/mteb/pull/469 because it's not a kwarg that MTEB tasks provide but rather users can provide themselves if they need to like done e.g. [here](https://github.com/ContextualAI/gritlm/blob/9883da1e77812e6ba2c107dc7b65d8c5ddc7396b/evaluation/eval_mteb.py#L1196) with instructions. Also most models do not even use prompts 🤔 cc @KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
Ahh yep that is a mistake. The goal was in the beginning to allow for prompt inputs when running the task. Currently it is not supported though.
