### ISSUE TITLE
[BUG] MalteseNewsClassification fails with KeyError

### ISSUE THREAD

**Issue by dokato** [embeddings-benchmark/mteb#810]
Has something changed in MultiLabel classification lately @x-tabdeveloping ? I can't run the Maltese task anymore. Full stacktrace below.

After `dataset_transform` call the data structure looks correct:

```py
DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 10784
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2293
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 2297
    })
})
```

but then in `_evaluate_subset` it only gets:
```
Dataset({
        features: ['text', 'label'],
        num_rows: 10784
    })
```

```
Error while evaluating MalteseNewsClassification: "Column train not in the dataset. Current columns in the dataset: ['text', 'label']"
Traceback (most recent call last):
  File "/Users/user/proj/mteb/mteb/tasks/MultiLabelClassification/mlt/MalteseNewsClassification.py", line 66, in <module>
    evaluation.run(model)
  File "/Users/user/proj/mteb/mteb/evaluation/MTEB.py", line 365, in run
    raise e
  File "/Users/user/proj/mteb/mteb/evaluation/MTEB.py", line 331, in run
    results, tick, tock = self._run_eval(
  File "/Users/user/proj/mteb/mteb/evaluation/MTEB.py", line 227, in _run_eval
    results = task.evaluate(model, split, output_folder=output_folder, **kwargs)
  File "/Users/user/proj/mteb/mteb/abstasks/AbsTask.py", line 115, in evaluate
    scores[hf_subset] = self._evaluate_subset(model, data_split, **kwargs)
  File "/Users/user/proj/mteb/mteb/abstasks/AbsTaskMultilabelClassification.py", line 80, in _evaluate_subset
    train_split = dataset[train_split]
  File "/Users/user/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2861, in __getitem__
    return self._getitem(key)
  File "/Users/user/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2845, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/Users/user/anaconda3/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 584, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/Users/user/anaconda3/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 521, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['text', 'label']"
```

**Comment by isaac-chung** [comment]
Thanks for raising this. It's more due to the inconsistency in passing in a DatasetDict or the dataset (split). I can take a look at the PR.
