### ISSUE TITLE
KeyError: 'validation' for RedditClustering and StackOverflowDupQuestions

### ISSUE THREAD

**Issue by XudongOliverShen** [embeddings-benchmark/mteb#93]
Is the validation set used for RedditClustering and StackOverflowDupQuestions? Related to #83 and #84.

-----
2022-12-16 05:26:27.662809 >>> RedditClustering
Traceback (most recent call last):
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/mteb/abstasks/AbsTaskClustering.py", line 17, in evaluate
    for cluster_set in tqdm.tqdm(self.dataset[split], desc="Clustering"):
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'

2022-12-16 05:26:39.846393 >>> StackOverflowDupQuestions
Traceback (most recent call last):
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/mteb/evaluation/MTEB.py", line 235, in run
    results = task.evaluate(model, split, **kwargs)
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/mteb/abstasks/AbsTaskReranking.py", line 21, in evaluate
    data_split = self.dataset[split]
  File "/home/aiops/shenxd/Dependency/anaconda3/envs/HuggingFace/lib/python3.7/site-packages/datasets/dataset_dict.py", line 57, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'

**Comment by Muennighoff** [comment]
Thanks for finding this! Just removed them, so you can reinstall mteb from source `pip install git+https://github.com/embeddings-benchmark/mteb.git` or just specify the eval_split when running, e.g.:
`eval_splits = ["validation"] if task == "MSMARCO" else ["test"]`
`evaluation.run(..., eval_splits=eval_splits)`
