### ISSUE TITLE
Error for loading ArxivClusteringP2P

### ISSUE THREAD

**Issue by hsl89** [embeddings-benchmark/mteb#94]
Hello @Muennighoff , I encountered the following issue when loading ArxivClusteringP2P dataset

repro
```
from mteb import MTEB

def test_loading_data():
    eval = MTEB(tasks=["ArxivClusteringP2P"])
    eval.load_tasks_data()
    return 


if __name__ == "__main__":
    test_loading_data()
```
output: 
```
Generating test split: 23 examples [00:04,  6.38 examples/s]Failed to read file '/root/.cache/huggingface/datasets/downloads/extracted/2368c5e45f666e09c88b163b1db73ad115ce53e3954755e8936da145b036ae4b' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Missing a closing quotation mark in string. in row 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/datasets/packaged_modules/json/json.py", line 153, in _generate_tables
    dataset = json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 25447588)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1817, in _prepare_split_single
    for _, table in generator:
  File "/usr/local/lib/python3.8/dist-packages/datasets/packaged_modules/json/json.py", line 156, in _generate_tables
    raise e
  File "/usr/local/lib/python3.8/dist-packages/datasets/packaged_modules/json/json.py", line 132, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow/_json.pyx", line 259, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Missing a closing quotation mark in string. in row 0
```

**Comment by Muennighoff** [comment]
> from mteb import MTEB
> 
> def test_loading_data():
>     eval = MTEB(tasks=["ArxivClusteringP2P"])
>     eval.load_tasks_data()
>     return 
> 
> 
> if __name__ == "__main__":
>     test_loading_data()

Hmm the code works fine for me, see the colab below:
https://colab.research.google.com/drive/1KnLPUIA3iU0mMambkAoAF7UINj3-swBy?usp=sharing

Can you try update to the latest package versions?

**Comment by hsl89** [comment]
I probably just got unlucky, the downloaded data file was corrupted. The issue is resolved after I deleted everything in the cache and re-downloaded the data.
