### ISSUE TITLE
KeyError: 'default'

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#969]
Got the below error when running https://github.com/embeddings-benchmark/mteb/blob/main/scripts/mmteb/running_model/create_slurm_jobs.py
```bash
INFO:mteb.cli:Running with parameters: Namespace(model='sentence-transformers/all-MiniLM-L6-v2', task_types=None, categories=None, tasks=['FloresBitextMining'], languages=None, device=None, output_folder='/data/niklas/mteb/results', verbosity=2, co2_tracker=True, eval_splits=None, model_revision=None, func=<function run at 0x7f75f4d4f400>)
/env/lib/conda/gritkto/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
─────────────────────────────── Selected tasks  ────────────────────────────────
BitextMining
    - FloresBitextMining, s2s, multilingual 41412 / 41412 langs


INFO:mteb.evaluation.MTEB:

********************** Evaluating FloresBitextMining **********************

.....shortened.....


ERROR:mteb.evaluation.MTEB:Error while evaluating FloresBitextMining: 'default'
Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 362, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 118, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 388, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 367, in run
    mteb_task_result = MTEBResults.from_task_results(
  File "/data/niklas/mteb/mteb/MTEBResults.py", line 89, in from_task_results
    eval_langs = subset2langscripts[hf_subset]
KeyError: 'default'

```

**Comment by isaac-chung** [comment]
Confirming that I can reproduce this from `main` by running 
```
mteb run -t FloresBitextMining -m sentence-transformers/all-MiniLM-L6-v2 --model_revision 8b3219a92973c328a8e22fadcfa821b5dc75636a
```

A quick look points me to https://github.com/embeddings-benchmark/mteb/blob/81882aa6bab85dbf12420cb196cb5bfa13deb550/mteb/abstasks/AbsTaskBitextMining.py#L36. FloresBitextMining does have `parallel_subsets = True`, so this will be run:
```python
scores["default"] = self._evaluate_subset(
                model,
                self.dataset[split],  # type: ignore
                parallel=True,
                **kwargs,
            )
```

**Comment by KennethEnevoldsen** [comment]
@loicmagne do you know what is happening here? It might be a conflict between your changes and future changes (we should probably add a test for a parallel_subsets=True dataset.

**Comment by isaac-chung** [comment]
The most recent change points to https://github.com/embeddings-benchmark/mteb/pull/759/files

**Comment by imenelydiaker** [comment]
Yeah it's related to #759, Flores has just a default HF subset (actually the `task.hf_subset` value is an empty list []), and language pairs are created when loading the dataset. 

Maybe we can fix it by replacing `hf_subsets` by `extend_lang_pairs()` result (the language pairs). I'm testing it 🤔
