### ISSUE TITLE
LLM2Vec inference error

### ISSUE THREAD

**Issue by AlexeyVatolin** [embeddings-benchmark/mteb#997]
When running Mistral or shared Sheared-LLaMA model from the LLM2Vec series, an error occurs, traceback below
```
ERROR:mteb.evaluation.MTEB:Error while evaluating AmazonCounterfactualClassification: Can't pickle local object 'add_hook_to_module.<locals>.new_forward'
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/llm_emb/bin/mteb", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/cli.py", line 362, in main
    args.func(args)
  File "/home/admin/vatolin/experiments/mteb/mteb/cli.py", line 118, in run
    eval.run(
  File "/home/admin/vatolin/experiments/mteb/mteb/evaluation/MTEB.py", line 388, in run
    raise e
  File "/home/admin/vatolin/experiments/mteb/mteb/evaluation/MTEB.py", line 354, in run
    results, tick, tock = self._run_eval(
                          ^^^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/evaluation/MTEB.py", line 251, in _run_eval
    results = task.evaluate(model, split, output_folder=output_folder, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/abstasks/AbsTaskClassification.py", line 86, in evaluate
    scores[hf_subset] = self._evaluate_subset(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/abstasks/AbsTaskClassification.py", line 145, in _evaluate_subset
    scores_exp, test_cache = evaluator(model, test_cache=test_cache)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/evaluation/evaluators/ClassificationEvaluator.py", line 342, in __call__
    X_train = model_encode(
              ^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/evaluation/evaluators/model_encode.py", line 26, in model_encode
    embeddings = model.encode(sentences, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/vatolin/experiments/mteb/mteb/models/llm2vec_models.py", line 65, in encode
    return self.model.encode(sentences, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/llm_emb/code/llm2vec/llm2vec/llm2vec.py", line 333, in encode
    for result in p.map(
                  ^^^^^^
  File "/home/admin/miniconda3/envs/llm_emb/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/envs/llm_emb/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/admin/miniconda3/envs/llm_emb/lib/python3.12/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/home/admin/miniconda3/envs/llm_emb/lib/python3.12/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/miniconda3/envs/llm_emb/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'add_hook_to_module.<locals>.new_forward'
[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```
I think it's a bug related multiprocess inference ([code here](https://github.com/McGill-NLP/llm2vec/blob/main/llm2vec/llm2vec.py#L347-L353)). It only occurs with 2 or more GPUs. Most likely this error is reproduced on all models, but have not tested.

**Comment by KennethEnevoldsen** [comment]
@AlexeyVatolin seems like this error is related to the LLM2Vec implementation. From my understanding of the error, I would say that it belongs over at their repository.

Tagging @vaibhavad as he overlaps on both MTEB and LLM2Vec

**Comment by vaibhavad** [comment]
@AlexeyVatolin - Thanks for raising this. I had not tested multi-gpu inference with MTEB integration, let me look into this now.

**Comment by vaibhavad** [comment]
Hi @AlexeyVatolin,

I found the issue, it was about properly mapping `device` to `device_map`.

I have tested the two approaches below to run llm2vec on 2-GPU setup.


**bash**
```bash
mteb run -m McGill-NLP/LLM2Vec-Sheared-LLaMA-mntp-supervised -t AmazonCounterfactualClassification
```

**python**
```python
import mteb

if __name__ == "__main__":
    model_name = "McGill-NLP/LLM2Vec-Sheared-LLaMA-mntp-supervised"
    model = mteb.get_model(model_name)
    tasks = mteb.get_tasks(tasks=["AmazonCounterfactualClassification"])
    evaluation = mteb.MTEB(tasks=tasks)
    results = evaluation.run(model, output_folder="results")
```

Both are working with the fix in #1020

**Comment by tianyumyum** [comment]
@vaibhavad hello！
![Uploading WechatIMG601.jpg…]()

I don't get an error when using the command line, but I get an error Bus error (core dumped) when using python files.

**Comment by tianyumyum** [comment]
@vaibhavad Hello![WechatIMG601](https://github.com/user-attachments/assets/3fff2a9d-0d1a-4efe-a00c-9eb1daf67617)
I don't get an error when using the command line, but I get an error Bus error (core dumped) when using python files.
I just run the same code as you listed above.
